/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Dieta;
import Modelo.MenuDiario;
import Modelo.Paciente;
import Persistencia.DietaData;
import Persistencia.MenuDiarioData;
import Vistas.Renglon.RenglonLista;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tomi
 */
public class DetallePaciente extends javax.swing.JPanel {

    /**
     * Creates new form DetallesDieta
     */
    Paciente paciente;
    DietaData repoDieta;
    MenuDiarioData repoMenu;

    public DetallePaciente(Paciente paciente) {
        this.paciente = paciente;
        this.repoDieta = DietaData.getRepo();
        initComponents();
        labelPaciente.setText("Nombre: " + paciente.getNombre());
        labelDNI.setText("DNI: " + paciente.getDni());
        labelPesoActual.setText("Peso actual: " + paciente.getPesoActual() + "kg");
        labelTalla.setText("Talla: " + paciente.getAltura() + "cm");
        labelEdad.setText("Edad: " + paciente.getEdad());
        labelIMC.setText(String.format("IMC: %.2f", paciente.calcularIMC()));
        llenarTablaDietas(null);
        tablaDietas.setDefaultEditor(Object.class, null);
        tablaDietas.setSelectionMode(0);
        tablaMenu.setDefaultEditor(Object.class, null);
        tablaMenu.setSelectionMode(0);
    }

    public void llenarTablaDietas(List<Dieta> dietas) {
        var header = new String[]{"Nombre", "Calorias", "Peso objetivo", "Fecha inicio", "Estado"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        tablaDietas.setModel(model);

        if (dietas == null) {
            dietas = repoDieta.getByPacienteanddieta(paciente.getNroPaciente(), checkboxActivas.isSelected());
            if (dietas.isEmpty()) {
                llenarTablaMenu();
                return;
            } else {
                jButton1.setVisible(false);
            }
        }
        btnBaja.setVisible(!checkboxActivas.isSelected());

        for (var dieta : dietas) {
            model.addRow(new Object[]{
                dieta,
                dieta.getTotalCalorias(),
                dieta.getPesoObjetivo(),
                dieta.getFechaInicio(),
                dieta.getBaja() ? "Finalizada" : "En curso"
            });
        }
        llenarTablaMenu();
    }

    public void llenarTablaMenu() {
        var header = new String[]{"Nombre", "Calorias", "Día"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        tablaMenu.setModel(model);

        Dieta dieta = getDietaSeleccionada();
        if (dieta == null || dieta.getMenus().isEmpty()) {
            return;
        }

        for (var menu : dieta.getMenu()) {
            model.addRow(new Object[]{
                menu,
                menu.getCaloriasDelMenu(),
                menu.getDia()
            });
        }
    }

    public Dieta getDietaSeleccionada() {
        Dieta dieta = null;
        try {
            var y = tablaDietas.getSelectedRow();
            y = y < 0 ? 0 : y;
            dieta = (Dieta) tablaDietas.getValueAt(y, 0);
        } catch (Exception ex) {
        }
        return dieta;
    }

    public void CargarMenus() {

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelPaciente = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDietas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        labelPesoActual = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelTalla = new javax.swing.JLabel();
        labelIMC = new javax.swing.JLabel();
        checkboxActivas = new javax.swing.JCheckBox();

        jButton4.setText("Remover entrada");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar entrada");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelPaciente.setText("Paciente: ");

        labelDNI.setText("DNI: ");

        jButton1.setText("Nueva dieta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        tablaDietas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDietas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDietasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDietas);

        jLabel9.setText("Lista dietas");

        jLabel10.setText("Menu dieta");

        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMenuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMenu);

        labelPesoActual.setText("Peso actual: ");

        labelEdad.setText("Edad: ");

        labelTalla.setText("Talla: ");

        labelIMC.setText("IMC: ");

        checkboxActivas.setText("Finalizadas");
        checkboxActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActivasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPaciente)
                                    .addComponent(labelDNI))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEdad)
                                    .addComponent(labelTalla))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelIMC))
                                    .addComponent(labelPesoActual))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkboxActivas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(232, 232, 232))))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPaciente)
                    .addComponent(labelPesoActual)
                    .addComponent(labelEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDNI)
                    .addComponent(labelTalla)
                    .addComponent(labelIMC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnBaja)
                    .addComponent(checkboxActivas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String inputNombre = null;
        Float pesoObjetivo = null;

        try {
            inputNombre = JOptionPane.showInputDialog("Ingrese nombre para la nueva dieta").trim();
        } catch (Exception ex) {
            return;
        }
        if (inputNombre.isEmpty()) {
            return;
        }
        while (pesoObjetivo == null) {
            try {
                pesoObjetivo = Float.valueOf(JOptionPane.showInputDialog("Ingrese peso objetivo").trim());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Operación abortada.");
                return;
            }
        }
        Dieta dieta = new Dieta(inputNombre, LocalDate.now(), null, paciente.getPesoActual(), 0, pesoObjetivo, false, 0, paciente);
        dieta.setPesoObjetivo(pesoObjetivo);
        repoDieta.save(dieta);

        llenarTablaDietas(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
        var dieta = (Dieta) getDietaSeleccionada();
        if (dieta == null || dieta.getBaja() == true) {
            return;
        }

        var res = JOptionPane.showConfirmDialog(null, "¿Realmente desea dar de baja la dieta seleccionada?");
        if (res != 0) {
            return;
        }

        dieta.setFechaFinal(LocalDate.now());
        dieta.setBaja(true);
        dieta.setPesoFinal(paciente.getPesoActual());
        repoDieta.update(dieta);
        llenarTablaDietas(null);
        if (tablaDietas.getRowCount() == 0) {
            jButton1.setVisible(true);
        }
    }//GEN-LAST:event_btnBajaActionPerformed


    private void tablaDietasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDietasMouseClicked
        // TODO add your handling code here:
        llenarTablaMenu();
    }//GEN-LAST:event_tablaDietasMouseClicked

    private void checkboxActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActivasActionPerformed
        // TODO add your handling code here:
        llenarTablaDietas(null);
    }//GEN-LAST:event_checkboxActivasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tablaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMenuMouseClicked
        // TODO add your handling code here:1
        if (evt.getClickCount() == 2) {
            MenuDiario Menu = getMenuSeleccionado();

            RenglonLista detalleMenu = new RenglonLista(Menu);

            JFrame nuevaVista = new JFrame("Nuevo Paciente");
            nuevaVista.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            nuevaVista.getContentPane().add(detalleMenu);
            nuevaVista.pack();
            nuevaVista.setVisible(true);
            nuevaVista.setLocation(585, 60);
        }
    }//GEN-LAST:event_tablaMenuMouseClicked


    /* 
    MenuDiario Menu = getMenuSeleccionado();
            RenglonLista detalleMenu = new RenglonLista();
            var principal = Principal.getPrincipal();
            principal.ShowPanel(detalleMenu)
    
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JCheckBox checkboxActivas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelIMC;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JLabel labelPesoActual;
    private javax.swing.JLabel labelTalla;
    private javax.swing.JTable tablaDietas;
    private javax.swing.JTable tablaMenu;
    // End of variables declaration//GEN-END:variables

    public MenuDiario getMenuSeleccionado() {
        int rowSelected = tablaMenu.getSelectedRow();
        MenuDiario men = null;
        if (rowSelected != -1) { // Nos sirve para verificar si la tabla esta seleccionada

            men = (MenuDiario) tablaMenu.getValueAt(rowSelected, 0);
        }
        return men;
    }

}
