/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Modelo.Paciente;
import Modelo.Registro;
import Persistencia.PacienteData;
import Persistencia.RegistroData;
import chart.ModelChart;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author Tomi
 */
public class ProgresoPaciente extends javax.swing.JPanel {

    private RegistroData regisData = RegistroData.getRepo();
    private PacienteData pacData = PacienteData.getRepo();
    private Paciente paciente;

    /**
     * Creates new form EstadisticasPaciente
     */
    public ProgresoPaciente(Paciente paciente) {
        this.paciente = paciente;
        initComponents();
        graficoLinea();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graficoLinea = new chart.LineChart();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graficoLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graficoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chart.LineChart graficoLinea;
    // End of variables declaration//GEN-END:variables

    public void graficoLinea() {
        
        List<Registro> datosRegistro = regisData.RegistroPaciente(paciente.getNroPaciente());

        graficoLinea.addLegend(paciente.getNombre(), new Color(54, 4, 143), new Color(104, 49, 200));

        for (Registro regist : datosRegistro) {
            graficoLinea.addData(new ModelChart(regist.getFechaRegistro().toString(), new double[]{regist.getPeso()}));
        }
        graficoLinea.start();

    }
}

